services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Dubai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password_123"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    container_name: flask-web
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "5000"   # internal only; Nginx will proxy to this

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"    # change to "80:80" if port 80 is free
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  mysql_data:
